databases:
  - name: expense
    databaseName: expense_xlsq
    user: expense_xlsq_user

services:
  - type: web
    name: expenses-app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: expense
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false