databases:
  - name: budget
    databaseName: budget_e77t
    user: budget_e77t_user

services:
  - type: web
    name: budget
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_e77t
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false