databases:
  - name: budget
    databaseName: budget_dgtx
    user: budget_dgtx_user

services:
  - type: web
    name: budget
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_dgtx
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false